fix(k3d): mount host volume for PVCs
rivet-gg/rivet pull request #1018
Opened 2024-07-31 23:02 UTC by MasterPtato

## Changes

2024-07-31 23:03 UTC, MasterPtato commented
* **#1018** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1018?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-02 02:26 UTC, NathanFlurry requested changes

2024-08-02 02:26 UTC, NathanFlurry commented on lib/bolt/core/src/dep/terraform/gen.rs
> +		json!(ctx.gen_path().join("volumes").display().to_string()),
this should be a new dir in the root. gen should be able to be deleted safely.

2024-08-16 05:06 UTC, NathanFlurry approved these changes

2024-08-16 05:09 UTC, merged