fix: add priority class to nats
rivet-gg/rivet pull request #1019
Opened 2024-07-31 23:19 UTC by MasterPtato

## Changes

2024-07-31 23:19 UTC, MasterPtato commented
* **#1019** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1019?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-02 02:28 UTC, NathanFlurry requested changes

2024-08-02 02:28 UTC, NathanFlurry commented on infra/tf/k8s_infra/nats.tf
>  		promExporter = {
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line +17]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->remove this<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1019?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-08-06 17:03 UTC, MasterPtato commented on infra/tf/k8s_infra/nats.tf
>  		promExporter = {
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line +17]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->```suggestion
```<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1019?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-08-06 21:09 UTC, NathanFlurry approved these changes

2024-08-06 21:13 UTC, merged