feat: add region proxying to actor client
rivet-gg/rivet pull request #1540
Opened 2024-12-06 01:52 UTC by MasterPtato

## Changes

2024-12-06 01:52 UTC, MasterPtato commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1540?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1540** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1540?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1540?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#1538** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1538?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1535** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#1539](https://github.com/rivet-gg/rivet/pull/1539) <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1539?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-06 01:55 UTC, MasterPtato commented
@NathanFlurry still have to publish the npm package

2024-12-09 18:50 UTC, NathanFlurry requested changes

2024-12-09 18:50 UTC, NathanFlurry commented on sdks/actors/client/src/client.ts
> +			region: (await this.#resolveRegion()).id,
This should be cached locally for 48h. Otherwise, this will add significant latency to creating new actors.

2024-12-10 05:26 UTC, NathanFlurry approved these changes

2024-12-10 20:07 UTC, closed without merging