fix: add back api docs
rivet-gg/rivet pull request #1549
Opened 2024-12-07 00:51 UTC by MasterPtato

## Changes

2024-12-07 00:51 UTC, MasterPtato commented
* **#1549** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1549?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1549?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-09 18:46 UTC, NathanFlurry requested changes

2024-12-09 18:46 UTC, NathanFlurry commented on docs/src/content/docs/api/actor/get.mdx
> +Gets a dynamic actor.## Code Examples
this didn't gen correctly

2024-12-10 05:28 UTC, NathanFlurry approved these changes

2024-12-10 20:03 UTC, closed without merging