Decrease select_with_timeout to fix 520 error
rivet-gg/rivet pull request #287
Opened 2023-12-21 03:07 UTC by NathanFlurry

## Changes

2023-12-21 03:08 UTC, NathanFlurry commented
Current dependencies on/for this PR:
* `main`
  * **PR #287** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/287?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #288** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/288?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/287?utm_source=stack-comment).

2023-12-21 04:48 UTC, AngelOnFira commented on lib/util/macros/src/lib.rs
> +const DEFAULT_TIMEOUT: u64 = 45 * 1000;
It's a bit hard to know what this magic number means when it's beside the doc saying "1 min", is there a way to make this a bit more clear? Maybe even having a link to the new API_TIMEOUTS.md doc.

2023-12-21 04:48 UTC, AngelOnFira commented on infra/tf/k8s_infra/traefik.tf
> +			"--entryPoints.websecure.transport.lifeCycle.graceTimeOut=45s",
Not sure if the math here is correct, wouldn't an extra 15s grace period put it up to `75s`?

2023-12-21 04:49 UTC, AngelOnFira commented on docs/infrastructure/API_TIMEOUTS.md
> +We assume that all requests should take less than. Many load balancers have 60s configured as default timeout.
Missing end of sentence:

> We assume that all requests should take less than...

2023-12-21 04:49 UTC, AngelOnFira requested changes
Some clarity requests

2023-12-22 20:00 UTC, MasterPtato reviewed
What exactly caused the 520 and why was decreasing the timeout to 40s a fix? Was it traefik's 60 second timeout? Shouldnt we be able to configure that? I don't understand from the docs

2023-12-23 18:54 UTC, NathanFlurry commented
> What exactly caused the 520 and why was decreasing the timeout to 40s a fix? Was it traefik's 60 second timeout? Shouldnt we be able to configure that? I don't understand from the docs

This didn't fix the 520, but it's still good to clean it up. I'm fairly certain it's something between CF & AWS.

2023-12-23 19:46 UTC, AngelOnFira approved these changes

2023-12-23 19:51 UTC, merged