Add chirp interop flag
rivet-gg/rivet pull request #299
Opened 2023-12-24 22:29 UTC by NathanFlurry

Fixes CLI-47

2023-12-24 22:29 UTC, NathanFlurry commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/299?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #298** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/298?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #299** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/299?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/299?utm_source=stack-comment).

2023-12-25 15:57 UTC, AngelOnFira approved these changes

2023-12-25 18:40 UTC, MasterPtato requested changes

2023-12-25 18:40 UTC, MasterPtato commented on proto/chirp.proto
> -
Does this affect any of our grafana dashboards?

2023-12-25 18:40 UTC, MasterPtato commented on lib/chirp/worker/src/manager.rs
> +					if let Some(chirp::response::err::Kind::BadRequest(error)) = &err_proto.kind {
When would a `BadRequest` error be recursive?

2023-12-25 18:40 UTC, MasterPtato commented on lib/chirp/worker/src/manager.rs
> +							let error_code_str = "__UNKNOWN__".to_string();
Does this make all internal requests have an unknown error code in grafana?

2023-12-29 00:56 UTC, MasterPtato commented
How were each of the threads resolved?

2023-12-29 04:33 UTC, NathanFlurry commented
> How were each of the threads resolved?

I resolved them instinctively. I should've left them open mb.

2023-12-29 17:31 UTC, NathanFlurry commented
@MasterPtato is this pr good to merge? needs an approval.

2023-12-29 17:37 UTC, MasterPtato approved these changes

2023-12-29 17:43 UTC, merged