Import fmt changes
rivet-gg/rivet pull request #308
Opened 2023-12-30 17:53 UTC by AngelOnFira

## Changes

2023-12-30 17:54 UTC, AngelOnFira commented
Current dependencies on/for this PR:
* `main`
  * **PR #308** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/308?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/308?utm_source=stack-comment).

2023-12-30 17:55 UTC, AngelOnFira commented on rustfmt.toml
> +group_imports = "StdExternalCrate"
These changes are the most important

2023-12-30 18:08 UTC, AngelOnFira reviewed
Maybe it would be best to add a script that overwrites the `rustfmt.toml`, does all the formatting with nightly (especially since it will need to go into many folders), then return `rustfmt.toml` to normal.

2023-12-31 01:24 UTC, NathanFlurry requested changes
Let's chat about how to handle this with unstable rust later

2024-01-02 02:04 UTC, AngelOnFira commented on fmt.sh
@NathanFlurry this is the new file that should be checked out in this PR

2024-01-02 18:40 UTC, MasterPtato approved these changes

2024-01-05 03:04 UTC, AngelOnFira commented on fmt.sh
Oops, I meant to comment on `fmt.sh`. I'm adding it to be the script that gets included to do the formatting. I imagine putting it in a deeper scripts folder would be better than the root, but just wanted to point out that it was the important file to look at.

2024-01-24 21:25 UTC, NathanFlurry approved these changes
yolo merge this

2024-01-24 23:02 UTC, AngelOnFira commented
I've changed it so this isn't the formatting, it's just the script. Format can be separate, making it easy to rebase.

2024-01-24 23:05 UTC, merged