Restack, add various fixes branch
rivet-gg/rivet pull request #373
Opened 2024-01-17 22:11 UTC by MasterPtato

## Changes

2024-01-17 22:12 UTC, MasterPtato commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/373?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #324** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/324?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #314** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/314?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #310** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/310?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #311** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/311?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #312** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/312?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #313** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/313?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #315** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/315?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #316** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/316?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #326** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/326?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #325** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/325?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #329** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/329?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #330** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/330?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #331** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/331?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                          * **PR #332** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/332?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                            * **PR #333** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/333?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                              * **PR #334** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/334?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                * **PR #335** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/335?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                  * **PR #336** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/336?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                    * **PR #337** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/337?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                      * **PR #338** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/338?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                        * **PR #339** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/339?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                          * **PR #340** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/340?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                            * **PR #341** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/341?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                              * **PR #342** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/342?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                                * **PR #343** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/343?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                                  * **PR #344** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/344?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                                    * **PR #345** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/345?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                                      * **PR #346** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/346?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                                                        * **PR #347** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/347?utm_source=stack-comment-icon" target [...]

2024-01-20 03:11 UTC, AngelOnFira approved these changes

2024-01-20 03:11 UTC, AngelOnFira commented on svc/pkg/faker/ops/job-template/templates/allocate.rs
> +	let _array = vec![0u8; size];
Oop, looks like the compiler still rolls with it 👍

2024-01-20 03:11 UTC, AngelOnFira requested changes
Oops meant to ask for fixes on the change to the Dockerfile

2024-01-22 18:20 UTC, MasterPtato commented on lib/job-runner/Dockerfile
> +COPY Cargo.toml Cargo.loc[k] .
Thats a good point. Removing it from the gitignore is probably the right play

2024-01-30 17:09 UTC, AngelOnFira approved these changes

2024-03-26 21:18 UTC, AngelOnFira requested changes

2024-03-26 21:18 UTC, AngelOnFira commented on lib/bolt/core/src/dep/cargo/cli.rs
>  						RUN apt-get update && apt-get install -y protobuf-compiler pkg-config libssl-dev g++
item dupe

2024-03-26 21:18 UTC, AngelOnFira commented on lib/bolt/core/src/dep/cargo/cli.rs
>  							&& tar xzf sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz \
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 159 to 163]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->double dupe<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/373?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-04-01 17:03 UTC, AngelOnFira approved these changes

2024-04-03 02:01 UTC, NathanFlurry approved these changes

2024-04-03 23:42 UTC, merged