Add admin login flag
rivet-gg/rivet pull request #389
Opened 2024-01-23 19:02 UTC by MasterPtato

## Changes

2024-01-23 19:02 UTC, MasterPtato commented
Current dependencies on/for this PR:
* `main`
  * **PR #389** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/389?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/389?utm_source=stack-comment).

2024-01-24 20:00 UTC, NathanFlurry requested changes

2024-01-24 20:00 UTC, NathanFlurry commented on lib/bolt/config/src/ns.rs
> +	pub admin_login: bool,
Nit: should be moved under smoething like `rivet.login.enable_admin` or something like that.

2024-01-25 01:35 UTC, NathanFlurry approved these changes
check is failing

2024-01-25 18:35 UTC, merged