Add timeouts, max in flight, compression to API and CDN
rivet-gg/rivet pull request #397
Opened 2024-01-26 18:59 UTC by MasterPtato

## Changes

2024-01-26 18:59 UTC, MasterPtato commented
Current dependencies on/for this PR:
* `main`
  * **PR #397** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/397?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/397?utm_source=stack-comment).

2024-01-26 19:02 UTC, MasterPtato commented
Untested, not sure how to go about testing the new timeouts

2024-01-30 07:32 UTC, NathanFlurry requested changes

2024-01-30 07:32 UTC, NathanFlurry commented on infra/tf/k8s_infra/traefik.tf
> +			# See docs/infrastructure/TIMEOUTS.md
Can we add a lower timeout on the ATS service specifically? Not sure how this converts to the CRD: https://doc.traefik.io/traefik/routing/services/#forwardingtimeouts

2024-01-30 07:32 UTC, NathanFlurry commented on svc/api/route/src/route/traefik/core.rs
>  		// "cdn-rate-limit".into(),
Remove the TODO. Rate limit will be done by CF.

2024-01-30 07:32 UTC, NathanFlurry commented on lib/api-helper/build/src/macro_util.rs
>  				// TODO: Test this is correct
If this is tested manually E2E, remove TODO

2024-01-30 07:33 UTC, NathanFlurry reviewed
bolt check failing too

2024-01-30 20:00 UTC, NathanFlurry approved these changes

2024-01-30 20:03 UTC, merged