Fix missing entitlements error not formatting
rivet-gg/rivet pull request #459
Opened 2024-02-05 21:24 UTC by MasterPtato

## Changes

2024-02-05 21:24 UTC, MasterPtato commented
Current dependencies on/for this PR:
* `main`
  * **PR #459** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/459?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/459?utm_source=stack-comment).

2024-02-05 21:26 UTC, AngelOnFira approved these changes

2024-02-05 21:51 UTC, NathanFlurry approved these changes

2024-02-05 21:52 UTC, NathanFlurry requested changes
needs a changelog entry

2024-02-16 20:44 UTC, NathanFlurry approved these changes

2024-02-16 22:49 UTC, merged