Cleanup
rivet-gg/rivet pull request #534
Opened 2024-02-23 01:23 UTC by MasterPtato

## Changes

2024-03-07 18:07 UTC, AngelOnFira approved these changes

2024-04-15 21:16 UTC, NathanFlurry approved these changes

2024-04-15 21:16 UTC, NathanFlurry commented on lib/bolt/core/src/dep/terraform/cli.rs
> +				vec![format!("-backend-config=conn_str={tf_conn_str}")]
why was reconfigure removed?

2024-04-15 21:16 UTC, NathanFlurry commented on lib/util/env/src/lib.rs
> +	pub fn account_id() -> &'static str {
can't this be simplified to make the lazy_static store the result with EnvVarError instead of an option?

2024-04-16 23:56 UTC, NathanFlurry requested changes
see comments

2024-04-17 21:07 UTC, NathanFlurry approved these changes

2024-05-18 00:01 UTC, MasterPtato commented
### Merge activity

* **May 17, 8:01 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/534) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

2024-05-18 01:15 UTC, merged