fix: route and access token tests
rivet-gg/rivet pull request #578
Opened 2024-03-21 17:15 UTC by MasterPtato

## Changes

2024-03-21 17:16 UTC, MasterPtato commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/578?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#578** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/578?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#573** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/573?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#572** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/572?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#571** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/571?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#570** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/570?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#566** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/566?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#565** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/565?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-01 16:03 UTC, AngelOnFira approved these changes

2024-04-01 16:03 UTC, AngelOnFira commented on .github/workflows/bolt-test.yaml
> +        uses: mxschmitt/action-tmate@v3
This is pretty dope, do we care about security at all?

https://github.com/mxschmitt/action-tmate?tab=readme-ov-file#use-registered-public-ssh-keys

2024-04-10 16:09 UTC, AngelOnFira approved these changes

2024-04-15 20:43 UTC, NathanFlurry requested changes

2024-04-15 20:43 UTC, NathanFlurry commented on svc/api/route/tests/basic.rs
> +		tokio::time::sleep(std::time::Duration::from_secs(5)).await;
needs a short comment on why we have a timeout

2024-04-16 18:26 UTC, NathanFlurry approved these changes

2024-04-18 21:11 UTC, merged