feat: add 1password integration docs
rivet-gg/rivet pull request #595
Opened 2024-03-26 02:27 UTC by MasterPtato

## Changes

2024-03-26 02:27 UTC, MasterPtato commented
* **#595** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/595?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-26 13:59 UTC, AngelOnFira requested changes

2024-03-26 13:59 UTC, AngelOnFira commented on docs/libraries/bolt/1PASSWORD_INTEGRATION.md
> +    Finally, run `bolt config push`.
nit: can we swap 1 and 2 if the 2nd is preferred?
```suggestion
1. #### Add the following to your namespace config (located in the `/namespaces` folder):

    You can [generate a service token](https://developer.1password.com/docs/service-accounts/) and write it to your `Bolt.local.toml` file to make config syncing quicker:

    ```toml
    [1password]
    	service-account-token = "..."
    ```

    Then, write the 1password config paths to your namespace file:

    ```toml
    [secrets.1password]
    	namespace_path = "op://<NAME OF 1PASSWORD VAULT>/<YOUR UUID>/<NAME OF CONFIG FIELD>"
    	secrets_path = "op://<NAME OF 1PASSWORD VAULT>/<YOUR UUID>/<NAME PF SECRETS FIELD>"
    ```

    Finally, run `bolt config push`.

2. #### Run `bolt config push` and input values manually

    This method will require you to input the 1password item paths and login details manually. It is recommended to use option 1 instead.

    Path formats:

    - Config: `op://<NAME OF 1PASSWORD VAULT>/<YOUR UUID>/<NAME OF CONFIG FIELD>`
    - Secrets: `op://<NAME OF 1PASSWORD VAULT>/<YOUR UUID>/<NAME PF SECRETS FIELD>`
```

2024-03-26 16:59 UTC, AngelOnFira approved these changes

2024-04-15 20:49 UTC, NathanFlurry approved these changes

2024-04-18 18:53 UTC, merged