feat: add provider api token to all linode calls
rivet-gg/rivet pull request #613
Opened 2024-03-27 23:22 UTC by MasterPtato

## Changes

2024-03-27 23:23 UTC, MasterPtato commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/613?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#613** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/613?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#599** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/599?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#598** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/598?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#382** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/382?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#381** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/381?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#380** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/380?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#300** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/300?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#373** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/373?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#377** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/377?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#597** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/597?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-01 15:51 UTC, AngelOnFira approved these changes

2024-04-01 15:51 UTC, AngelOnFira approved these changes

2024-04-14 23:56 UTC, NathanFlurry commented on svc/pkg/linode/standalone/gc/src/lib.rs
> +	let api_token = util::env::read_secret(&["linode", "token"]).await?;
Won't this only run for the main cluster? Don't we need to iterate over all clusters?

2024-04-14 23:59 UTC, NathanFlurry requested changes

2024-04-14 23:59 UTC, NathanFlurry commented on svc/pkg/linode/standalone/gc/src/lib.rs
> +	let api_token = util::env::read_secret(&["linode", "token"]).await?;
Won't this only run for the main cluster? Don't we need to iterate over all clusters?

2024-04-14 23:59 UTC, NathanFlurry commented on svc/pkg/linode/util/src/lib.rs
>  		let api_token = util::env::read_secret(&["linode", "token"]).await?;
This overrides the api token passed in

2024-04-14 23:59 UTC, NathanFlurry commented on svc/pkg/linode/util/src/lib.rs
>  		let api_token = util::env::read_secret(&["linode", "token"]).await?;
rust warning would've caught this, we need to clean these up :/

2024-04-14 23:59 UTC, NathanFlurry commented on svc/pkg/linode/util/src/lib.rs
> +	pub async fn new(api_token: &str) -> GlobalResult<Self> {
We're writing a lot of conditionals. Can we just pass in "override api token" as an optional and if not exists, read the default token?

2024-04-15 20:40 UTC, NathanFlurry approved these changes

2024-04-17 20:03 UTC, merged