feat: add service tokens
rivet-gg/rivet pull request #636
Opened 2024-04-05 04:52 UTC by NathanFlurry

Fixes RVT-3700
Fixes RVT-3702

2024-04-05 04:52 UTC, NathanFlurry commented
* **#636** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/636?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @NathanFlurry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-05 23:58 UTC, MasterPtato requested changes

2024-04-05 23:58 UTC, MasterPtato commented on fern/definition/cloud/games/tokens.yml
> +    createServiceToken:
This endpoint goes by "ServiceToken" whereas the namespace endpoint goes by "TokenService". Either one should be changed for consistency

2024-04-15 19:21 UTC, AngelOnFira requested changes

2024-04-15 19:21 UTC, AngelOnFira commented on docs/infrastructure/fern/GENERATING.md
I wrote my own docs for this in the script file parallel to this being written:
```bash
# To install fern, first clone the repo and check out the branch
# $ git clone https://github.com/rivet-gg/fern
# $ cd fern
# $ git checkout max/remove-headers
#
# Then, follow the instructions in SETUP.md and CONTRIBUTING.md to compile fern
# $ yarn
# $ yarn compile
# $ yarn dist:cli:dev
#
# Finally, run this with the path to the fern repo, say:
# $ FERN_REPO_PATH=~/fern ./oss/scripts/fern/gen.sh
```

I think we can remove mine, it makes more sense to go here. I'm going to make some other requests for things that could be a bit better in the writeup based on mine.

2024-04-15 19:21 UTC, AngelOnFira commented on docs/infrastructure/fern/GENERATING.md
> +gh repo clone rivet-gg/fern
Can we instead use `git` here? I think people will be less familiar with `gh`, and potentially not know what the command would do.

```suggestion
git clone https://github.com/rivet-gg/fern
```

2024-04-15 19:21 UTC, AngelOnFira commented on docs/infrastructure/fern/GENERATING.md
> +yarn dist:cli:dev
I have `yarn compile` right before `yarn dist:cli:dev`, is it needed?

2024-04-15 19:21 UTC, AngelOnFira commented on docs/infrastructure/fern/GENERATING.md
> +gh repo clone rivet-gg/fern
In my version, I said to check out `max/remove-headers`. Is that now included in trunk?

2024-04-15 19:27 UTC, MasterPtato approved these changes

2024-06-02 18:59 UTC, NathanFlurry commented
Closing in favor of OpenGB

2024-06-02 18:59 UTC, closed without merging