docs: Add doc about creating new endpoints
rivet-gg/rivet pull request #645
Opened 2024-04-09 17:20 UTC by AngelOnFira

## Changes

2024-04-09 17:20 UTC, AngelOnFira commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/645?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#645** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/645?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#644** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/644?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#643** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/643?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#642** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/642?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AngelOnFira and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-11 22:35 UTC, MasterPtato commented on docs/getting_started/ADDING_AN_ENDPOINT.md
> +3. If you added any enums to the `common.yml` file, you'll need to add/update the
This doesn't just apply to enums but structs too

2024-04-19 07:36 UTC, NathanFlurry requested changes
still wip

2024-04-23 19:04 UTC, MasterPtato approved these changes

2024-04-24 05:03 UTC, NathanFlurry approved these changes

2024-04-25 19:17 UTC, merged