fix(fern): remove dupe fern gen from bad merge
rivet-gg/rivet pull request #725
Opened 2024-04-20 19:05 UTC by NathanFlurry

## Changes

2024-04-20 19:06 UTC, NathanFlurry commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/725?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#726** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/726?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#725** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/725?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#644** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/644?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#645](https://github.com/rivet-gg/rivet/pull/645) <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/645?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#717** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/717?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#643** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/643?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#642** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/642?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#701** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/701?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#700** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/700?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#632** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/632?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#633](https://github.com/rivet-gg/rivet/pull/633) <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/633?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#628** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/628?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#629](https://github.com/rivet-gg/rivet/pull/629) <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/629?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#613** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/613?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @NathanFlurry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-20 22:11 UTC, AngelOnFira requested changes

2024-04-20 22:11 UTC, AngelOnFira commented on scripts/fern/gen_inner.sh
> +exit 1
Is this meant to stay?

2024-04-22 16:30 UTC, MasterPtato approved these changes

2024-04-23 18:56 UTC, AngelOnFira commented
Does this need to be restacked? Seems that it's carrying the commits from the branch below it. Might be resolved once I merge mine.

2024-04-23 18:56 UTC, AngelOnFira approved these changes

2024-05-16 01:38 UTC, merged