feat: run sub workflows in the same process
rivet-gg/rivet pull request #789
Opened 2024-05-09 23:33 UTC by MasterPtato

## Changes

2024-05-09 23:33 UTC, MasterPtato commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/789?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#789** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/789?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#788** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/788?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#787** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/787?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#785** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/785?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#784** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/784?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#783** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/783?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#780** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/780?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-13 13:50 UTC, AngelOnFira approved these changes

2024-05-16 00:44 UTC, NathanFlurry requested changes

2024-05-16 00:44 UTC, NathanFlurry commented on lib/chirp-workflow/core/src/ctx/workflow.rs
> +			// TODO: This is redundant with the deserialization in `workflow.run` in the registry
ticket

2024-05-16 00:44 UTC, NathanFlurry commented on lib/chirp-workflow/core/src/ctx/workflow.rs
> +			// TODO: If a sub workflow is dispatched, then the worker is updated to include the sub worker
ticket

2024-05-16 00:44 UTC, NathanFlurry commented on lib/chirp-workflow/core/src/ctx/workflow.rs
> +		// TODO: Get rid of this step, this is redundant
ticket

2024-06-03 23:02 UTC, NathanFlurry approved these changes

2024-06-05 20:07 UTC, NathanFlurry approved these changes

2024-06-05 20:27 UTC, merged