feat(bolt): add k9s to nix-shell
rivet-gg/rivet pull request #903
Opened 2024-06-11 05:05 UTC by AngelOnFira

## Changes

2024-06-11 05:06 UTC, AngelOnFira commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/903?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#904** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/904?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#903** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/903?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#740** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/740?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#750](https://github.com/rivet-gg/rivet/pull/750) <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/750?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#759** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/759?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#751** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/751?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#755** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/755?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#747** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/747?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#743** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/743?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#754** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/754?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#741** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/741?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AngelOnFira and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-12 23:29 UTC, NathanFlurry requested changes
let's just add the alias, not the k9s dependency. trying to keep our nix deps as lightweight as possible, since that directly adds wait time for setting up a dev env.

2024-06-18 20:21 UTC, NathanFlurry commented
@AngelOnFira can you move #904 on to #740

2024-07-03 19:39 UTC, NathanFlurry commented
@AngelOnFira we can merge this if we remove k9s from the packages and just leave the alias. if you install it on the host system, k9s will work as expected.

2024-07-03 19:39 UTC, NathanFlurry commented
@AngelOnFira we can merge this if we remove k9s from the packages and just leave the alias. if you install it on the host system, k9s will work as expected.

2024-07-03 19:49 UTC, AngelOnFira commented
Oh ya, now that I'm not in a devcontainer that will be dope

2024-07-03 20:01 UTC, AngelOnFira commented on shell.nix
>  			kubernetes-helm
```suggestion
			kubectl
			kubernetes-helm
```

2024-07-06 18:11 UTC, NathanFlurry approved these changes

2024-07-09 22:57 UTC, MasterPtato approved these changes

2024-07-23 08:23 UTC, merged