chore: increase sql conn acquire rate limits
rivet-gg/rivet pull request #915
Opened 2024-06-14 21:16 UTC by NathanFlurry

## Changes

2024-06-14 21:16 UTC, NathanFlurry commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/915?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#915** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/915?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#914** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/914?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#913** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/913?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#912** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/912?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#911** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/911?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#908** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/908?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#907** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/907?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#905** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/905?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @NathanFlurry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-14 22:57 UTC, MasterPtato requested changes

2024-06-14 22:57 UTC, MasterPtato commented on lib/pools/src/utils/sql_query_macros.rs
>  			// Allow creating at most 5 connections at the same time
```suggestion
			// Allow creating at most 256 connections at the same time
```

2024-06-17 17:53 UTC, MasterPtato commented on svc/pkg/cluster/standalone/default-update/src/lib.rs
> +						PoolType::Job => {
Make sure to remove this once we enable the autoscaler for gg and ats

2024-06-17 17:53 UTC, MasterPtato approved these changes

2024-06-19 17:13 UTC, MasterPtato approved these changes

2024-06-19 22:39 UTC, merged