feat(clusters): static endpoint for gg nodes
rivet-gg/rivet pull request #921
Opened 2024-06-18 19:10 UTC by MasterPtato

## Changes

2024-06-18 19:10 UTC, MasterPtato commented
* **#921** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/921?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-24 04:38 UTC, NathanFlurry requested changes

2024-06-24 04:38 UTC, NathanFlurry commented on svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/traefik.rs
> +			rule = "Path(`/status`)"
won't this override any `/status` endpoints for game servers? unless their priority takes precedence, in which case we should add a comment noting that.

would be good to restrict this to a specific host, regardless.

2024-06-25 04:18 UTC, NathanFlurry requested changes

2024-06-25 04:18 UTC, NathanFlurry commented on svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/traefik.rs
> +		# Status router, always returns 200 code
this code doesn't do anything right? should be removed

2024-06-25 04:18 UTC, NathanFlurry commented on svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/traefik.rs
> +			rule = "Path(`/status`)"
also needs a host

2024-06-25 04:18 UTC, NathanFlurry commented on svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/traefik.rs
> +	Ok(formatdoc!(
nit: usually group *.tls.domain under the main block instead of alternating blocks. thx toml very cool

2024-06-26 17:46 UTC, NathanFlurry approved these changes

2024-06-26 17:46 UTC, NathanFlurry commented on svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/traefik.rs
> +	Ok(formatdoc!(
@MasterPtato oh jeez i'm blind i misread the http.services and http.routers on this comment

2024-06-26 17:49 UTC, merged