chore(clusters): remove git as a dependency for cluster util
rivet-gg/rivet pull request #931
Opened 2024-06-19 21:26 UTC by MasterPtato

## Changes

2024-06-19 21:26 UTC, MasterPtato commented
* **#931** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/931?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-24 04:23 UTC, NathanFlurry requested changes

2024-06-24 04:23 UTC, NathanFlurry commented on svc/pkg/cluster/util/build.rs
> +    let mut entries = fs::read_dir(path).await?;
i'm not sure this actually works. read_dir doesn't return a consistent order of results. i'd recommend pulling in a crate for this.

2024-06-25 04:03 UTC, NathanFlurry approved these changes

2024-06-25 04:06 UTC, merged