chore(k3d): disable volumes if using use_local_repo
rivet-gg/rivet pull request #954
Opened 2024-06-26 21:46 UTC by NathanFlurry

## Changes

2024-06-26 21:46 UTC, NathanFlurry commented
* **#954** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/954?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @NathanFlurry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-27 17:41 UTC, MasterPtato requested changes

2024-06-27 17:41 UTC, MasterPtato commented on lib/bolt/core/src/dep/terraform/gen.rs
> +	}
Should this also insert the var with value `false` if `use_local_repo` isn't set? The var in terraform isnt marked as optional

2024-07-03 00:58 UTC, MasterPtato approved these changes

2024-07-03 08:49 UTC, merged